joint_limits:
  left__wheel_joint:
    has_position_limits: false
    has_velocity_limits: true
    min_velocity: -16.7551608
    max_velocity: 16.7551608
    has_acceleration_limits: false
    min_acceleration: -1.0
    max_acceleration: 1.0
    has_jerk_limits: false
    max_jerk: 0.1
    min_jerk: -0.1
    has_effort_limits: false
    max_effort: 1.0
    min_effort: -1.0
    has_soft_limits: true
    soft_lower_limit: -15.0
    soft_upper_limit: 15.0
    k_position: 1.0
    k_velocity: 0.0001
  right__wheel_joint:
    has_position_limits: false
    has_velocity_limits: true
    min_velocity: -16.7551608
    max_velocity: 16.7551608
    has_acceleration_limits: false
    min_acceleration: -1.0
    max_acceleration: 1.0
    has_jerk_limits: false
    max_jerk: 0.1
    min_jerk: -0.1
    has_effort_limits: false
    max_effort: 1.0
    min_effort: -1.0
    has_soft_limits: true
    soft_lower_limit: -15.0
    soft_upper_limit: 15.0
    k_position: 0.01
    k_velocity: 0.0001